Introduce multiple partitions support to disk_image
Rootfses that should be written to disk as their own partition are
called *_ROOTFS instead of *_RAMDISK.

This change makes the config file clearer and more consistent. However
it changes the current behavior as the Dom0 RAMDISK (not ROOTFS) was
written to disk as its own partition before, and now it is not.

In the case of uboot-script-gen, dom0less guests cannot access disk
partitions yet (missing PV drivers support). Hence, if one or more domU
ROOTFSes are specified, print an error and exit. For dom0, base the
root= parameter generation on the presence of DOM0_ROOTFS.

Signed-off-by: Stefano Stabellini <stefano.stabellini@xilinx.com>

diff --git a/scripts/uboot-script-gen b/scripts/uboot-script-gen
--- a/scripts/uboot-script-gen
+++ b/scripts/uboot-script-gen
@@ -276,7 +276,7 @@ then
 fi
 if [[ ! $DOM0_CMD =~ root= ]]
 then
-    if test "$LOAD_CMD" = "tftpb"
+    if test -z "$DOM0_ROOTFS"
     then
         DOM0_CMD="$DOM0_CMD root=/dev/ram0"
     else
@@ -322,6 +322,12 @@ do
     if test -z "${DOMU_VCPUS[$i]}"
     then
         DOMU_VCPUS[$i]=1
+    fi
+    if test "${DOMU_ROOTFS[$i]}"
+    then
+        echo "Cannot handle non-ramdisk rootfses for dom0less VMs."
+        echo "DomUs with rootfses on disk need to be created from dom0 using xl."
+        exit 1
     fi
     i=$(( $i + 1 ))
 done
